### ISSUE TITLE
Exporting from justwatch

### ISSUE THREAD

**Issue by bagajohny** [DiegoFleitas/letterboxd-movie-justwatch#29]
I have a JustWatch watchlist that I want to export to Simkl. I am trying the method [of this repo.](https://github.com/ijanos/justwatchdumper) from ijanos.
@DiegoFleitas  you have already helped me before. Now I am stuck with the "xargs" step. I am getting following error,

![image](https://github.com/DiegoFleitas/letterboxd-movie-justwatch/assets/101859073/a36184de-0562-49a9-9592-00f976ee5f90)

I am using Windows 10 to do this. I have already extracted the URLs of my watchlist in a text file. Now what I am trying to do is 

> feed the text file to the download script with xargs.

How do I solve this error?

So far I have tried `Get-Content urls.txt | ForEach-Object { .\dl.sh $_ }` in PoweShell with the help of chatGPT but it is not working. It is opening multiple tabs in the firefox like this (screenshot below)

![image](https://github.com/DiegoFleitas/letterboxd-movie-justwatch/assets/101859073/6f8ca1ab-6b32-45e7-bf38-daae36264802)

**Comment by DiegoFleitas** [comment]
Hey, that's intended to be ran on a Unix system with a bash terminal. I assume you are trying to do it on Windows & with PowerShell so it's bound for the guide to not help you that much. Its good you are using ChatGPT to figure it out but you put an extra layer of complexity on the the task when your enviroment is so different. I think the easiest way you can spin up an environment like the guide expects would be using GitHub codespaces & go from there, its free but it is also time limited (60h time limit per month for the lower end codespaces or less time per month with a more powerful codespace but you should be good with the first)

![image](https://github.com/DiegoFleitas/letterboxd-movie-justwatch/assets/15369935/23be0553-0289-44db-b37e-982be6db4d43)

**Comment by DiegoFleitas** [comment]
Btw github issues & discussions are two different things, you correctly created a discussion before but this was created as an issue which is not the best way to talk about smt unrelated to repo, I'll close this issue
https://github.com/DiegoFleitas/letterboxd-movie-justwatch/discussions

**Comment by bagajohny** [comment]
> Btw github issues & discussions are two different things, you correctly created a discussion before but this was created as an issue which is not the best way to talk about smt unrelated to the repo, I'll close this issue https://github.com/DiegoFleitas/letterboxd-movie-justwatch/discussions

I didnt know. I will keep this in mind.

I will research more about how to use codespaces and next time create a discussion if I need any help.
